<?php
namespace Zodream\Helpers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:46.
 */
class ArrTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Arr
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Arr;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Helpers\Arr::first
     * @todo   Implement testFirst().
     */
    public function testFirst()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::toFile
     * @todo   Implement testToFile().
     */
    public function testToFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::toString
     * @todo   Implement testToString().
     */
    public function testToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::collapse
     * @todo   Implement testCollapse().
     */
    public function testCollapse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::except
     * @todo   Implement testExcept().
     */
    public function testExcept()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::forget
     * @todo   Implement testForget().
     */
    public function testForget()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::last
     * @todo   Implement testLast().
     */
    public function testLast()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::flatten
     * @todo   Implement testFlatten().
     */
    public function testFlatten()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::pluck
     * @todo   Implement testPluck().
     */
    public function testPluck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::dataGet
     * @todo   Implement testDataGet().
     */
    public function testDataGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::only
     * @todo   Implement testOnly().
     */
    public function testOnly()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::prepend
     * @todo   Implement testPrepend().
     */
    public function testPrepend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::pull
     * @todo   Implement testPull().
     */
    public function testPull()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::getValues
     * @todo   Implement testGetValues().
     */
    public function testGetValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::getChild
     * @todo   Implement testGetChild().
     */
    public function testGetChild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::getChildByArray
     * @todo   Implement testGetChildByArray().
     */
    public function testGetChildByArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::getChildWithStar
     * @todo   Implement testGetChildWithStar().
     */
    public function testGetChildWithStar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::combine
     * @todo   Implement testCombine().
     */
    public function testCombine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::isAssoc
     * @todo   Implement testIsAssoc().
     */
    public function testIsAssoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::split
     * @todo   Implement testSplit().
     */
    public function testSplit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::ucFirst
     * @todo   Implement testUcFirst().
     */
    public function testUcFirst()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::getKey
     * @todo   Implement testGetKey().
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::getColumn
     * @todo   Implement testGetColumn().
     */
    public function testGetColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::merge2D
     * @todo   Implement testMerge2D().
     */
    public function testMerge2D()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::inArray
     * @todo   Implement testInArray().
     */
    public function testInArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::sortByKey
     * @todo   Implement testSortByKey().
     */
    public function testSortByKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Arr::keyAndValue
     * @todo   Implement testKeyAndValue().
     */
    public function testKeyAndValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
