<?php
namespace Zodream\Helpers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:46.
 */
class StrTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Str
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Str;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Helpers\Str::value
     * @todo   Implement testValue().
     */
    public function testValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::contains
     * @todo   Implement testContains().
     */
    public function testContains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::repeat
     * @todo   Implement testRepeat().
     */
    public function testRepeat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::is
     * @todo   Implement testIs().
     */
    public function testIs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::random
     * @todo   Implement testRandom().
     */
    public function testRandom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::randomInt
     * @todo   Implement testRandomInt().
     */
    public function testRandomInt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::randomNumber
     * @todo   Implement testRandomNumber().
     */
    public function testRandomNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::randomBytes
     * @todo   Implement testRandomBytes().
     */
    public function testRandomBytes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::urlBindValue
     * @todo   Implement testUrlBindValue().
     */
    public function testUrlBindValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::quickRandom
     * @todo   Implement testQuickRandom().
     */
    public function testQuickRandom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::randomByNumber
     * @todo   Implement testRandomByNumber().
     */
    public function testRandomByNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::byteLength
     * @todo   Implement testByteLength().
     */
    public function testByteLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::explode
     * @todo   Implement testExplode().
     */
    public function testExplode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::multiExplode
     * @todo   Implement testMultiExplode().
     */
    public function testMultiExplode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::startsWith
     * @todo   Implement testStartsWith().
     */
    public function testStartsWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::endWith
     * @todo   Implement testEndWith().
     */
    public function testEndWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::firstReplace
     * @todo   Implement testFirstReplace().
     */
    public function testFirstReplace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::lastReplace
     * @todo   Implement testLastReplace().
     */
    public function testLastReplace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::studly
     * @todo   Implement testStudly().
     */
    public function testStudly()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::absLength
     * @todo   Implement testAbsLength().
     */
    public function testAbsLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::subString
     * @todo   Implement testSubString().
     */
    public function testSubString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Str::subStr
     * @todo   Implement testSubStr().
     */
    public function testSubStr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
