<?php
namespace Zodream\Helpers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:47.
 */
class TimeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Time
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Time;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Helpers\Time::format
     * @todo   Implement testFormat().
     */
    public function testFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Time::timestamp
     * @todo   Implement testTimestamp().
     */
    public function testTimestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Time::getBeginAndEndTime
     * @todo   Implement testGetBeginAndEndTime().
     */
    public function testGetBeginAndEndTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Time::isTimeAgo
     * @todo   Implement testIsTimeAgo().
     */
    public function testIsTimeAgo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Helpers\Time::millisecond
     * @todo   Implement testMillisecond().
     */
    public function testMillisecond()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
